In [1]:
from caveclient import CAVEclient

client = CAVEclient('minnie65_public')

In [2]:
def load_neuron(root_id, client):
    from skeleton_plot.skel_io import load_mw
    cloud_dir = 'https://storage.googleapis.com/allen-minnie-phase3/minniephase3-emily-pcg-skeletons/minnie_all/v661/meshworks'
    df = client.materialize.views.single_neurons(pt_root_id=root_id).query()
    if len(df)==0:
        raise ValueError(f'No pre-computed skeleton for root id {root_id}')
    else:
        return load_mw(cloud_dir, f'{root_id}_{df.iloc[0]["id"]}.h5')

In [33]:
ct_df = client.materialize.tables.allen_v1_column_types_slanted_ref().query()

The `client.materialize.tables` interface is experimental and might experience breaking changes before the feature is stabilized.

In [13]:
row = ct_df.query('cell_type=="MC"').sample()
root_id = row['pt_root_id'].values[0]

In [15]:
nrn = load_neuron(root_id, client)

The `client.materialize.views` interface is experimental and might experience breaking changes before the feature is stabilized.

In [22]:
nrn.path_length() / 1_000

7053.474

In [23]:
nrn.apply_mask( nrn.anno.is_axon.mesh_mask )

In [24]:
nrn.path_length() / 1_000

4231.0945

In [25]:
nrn.reset_mask()

In [26]:
nrn.path_length() / 1_000

7053.474

In [28]:
print('before', nrn.path_length() / 1_000)
with nrn.mask_context(nrn.anno.is_axon.mesh_mask):
    print('during', nrn.path_length() / 1_000)
print('after', nrn.path_length() / 1_000)

before 7053.474
during 4231.0945
after 7053.474

In [38]:
segs = nrn.segments()

In [42]:
nrn.mesh

In [43]:
nrn.skeleton.vertices

array([[619696., 403880., 932280.],
       [620136., 404312., 933360.],
       [621832., 402920., 932040.],
       ...,
       [937016., 324072., 941040.],
       [936200., 325440., 941120.],
       [758784., 475840., 879000.]])

In [39]:
len(segs)

208

In [46]:
segs[0]

JointMeshIndex([   2,    0,    1,    3,    4,    6,    5,    7,    9,
                   8,   10,   11,   13,   12,   14,   15,   16,   19,
                  17,   18,   21,   23,   29,   22,   27,   28,   30,
                  35,   20,   24,   25,   26,   33,   34,   47,   45,
                  46,   56,   75,   81,   89,   87,   88,   96,   97,
                 109,  122,  132,  150,  151,  167,  166,  181,  182,
                 192,  193,  195,  196,  194,  207,  226,  241,  257,
                 281,  284,  280,  309,  314,  334,  339,  340,  341,
                 373,  444,  435,  443,  519,  520,  512,  557,  619,
                 696,  697,  701,  773,  776,  772,  830,  882,  819,
                 822,  823,  824,  872,  873,  877,  932,  935,  996,
                 995, 1050, 1054, 1147, 1138, 1280, 1289, 1288, 1287,
                1432, 1442, 1297, 1443, 1542, 1433, 1535, 1536, 1537,
                1641, 1746])

In [48]:
nrn.anno.segment_properties.df

,area,area_factor,is_root,len,mesh_ind,r_eff,seg_num,strahler,vol,mesh_ind_filt
0,218746944,1.822408,False,128907.992188,0,148.196081,0,1,8894123520,0
1,218746944,1.822408,False,128907.992188,1,148.196081,0,1,8894123520,1
2,218746944,1.822408,False,128907.992188,2,148.196081,0,1,8894123520,2
3,218746944,1.822408,False,128907.992188,3,148.196081,0,1,8894123520,3
4,218746944,1.822408,False,128907.992188,4,148.196081,0,1,8894123520,4
...,...,...,...,...,...,...,...,...,...,...
7249,163468800,1.777503,False,93543.640625,7249,156.469783,206,1,7194905600,7249
7250,163468800,1.777503,False,93543.640625,7250,156.469783,206,1,7194905600,7250
7251,163468800,1.777503,False,93543.640625,7251,156.469783,206,1,7194905600,7251
7252,163468800,1.777503,False,93543.640625,7252,156.469783,206,1,7194905600,7252
7253,163468800,1.777503,False,93543.640625,7253,156.469783,206,1,7194905600,7253

In [49]:
nrn.anno.segment_properties.df.query('seg_num == 0')

,area,area_factor,is_root,len,mesh_ind,r_eff,seg_num,strahler,vol,mesh_ind_filt
0,218746944,1.822408,False,128907.992188,0,148.196081,0,1,8894123520,0
1,218746944,1.822408,False,128907.992188,1,148.196081,0,1,8894123520,1
2,218746944,1.822408,False,128907.992188,2,148.196081,0,1,8894123520,2
3,218746944,1.822408,False,128907.992188,3,148.196081,0,1,8894123520,3
4,218746944,1.822408,False,128907.992188,4,148.196081,0,1,8894123520,4
...,...,...,...,...,...,...,...,...,...,...
1536,218746944,1.822408,False,128907.992188,1536,148.196081,0,1,8894123520,1536
1537,218746944,1.822408,False,128907.992188,1537,148.196081,0,1,8894123520,1537
1542,218746944,1.822408,False,128907.992188,1542,148.196081,0,1,8894123520,1542
1641,218746944,1.822408,False,128907.992188,1641,148.196081,0,1,8894123520,1641
1746,218746944,1.822408,False,128907.992188,1746,148.196081,0,1,8894123520,1746

In [57]:
nrn.anno.post_syn.filter_query(
    segs[1].to_mesh_mask,
).df

,ctr_pt_position,id,post_pt_level2_id,post_pt_mesh_ind,post_pt_position,post_pt_root_id,post_pt_supervoxel_id,pre_pt_position,pre_pt_root_id,pre_pt_supervoxel_id,size,post_pt_mesh_ind_filt
6,"[163334, 97304, 22442]",136535032,159319716840605067,63,"[163402, 97284, 22443]",864691135323181212,87262122803161746,"[163306, 97400, 22439]",864691135124672791,87191754058975761,4460,63
12,"[181360, 105022, 22490]",166887693,161783653678974108,1767,"[181404, 105002, 22491]",864691135323181212,89726059641581397,"[181294, 104990, 22494]",864691135416719546,89726059641583815,6296,1767
65,"[162546, 96844, 22412]",130273030,159178910632772520,36,"[162572, 96774, 22415]",864691135323181212,87121316595288914,"[162518, 96920, 22417]",864691135125813783,87121316595291595,8004,36
69,"[163538, 97541, 22544]",138174971,159319785627189251,74,"[163464, 97538, 22536]",864691135323181212,87262191589296586,"[163428, 97516, 22538]",864691135124541463,87262191589297600,7552,74
166,"[162848, 97092, 22451]",130273372,159178979352249649,44,"[162786, 97118, 22444]",864691135323181212,87121385314796035,"[162836, 97076, 22458]",864691134060652829,87121385314802009,1740,44
...,...,...,...,...,...,...,...,...,...,...,...,...
7113,"[164068, 96859, 22502]",136663476,159390016865306178,77,"[164080, 96876, 22502]",864691135323181212,87332422827906425,"[164054, 96800, 22503]",864691135435747058,87332422827916088,2808,77
7114,"[176096, 102507, 22512]",159134090,161009253895636353,783,"[176074, 102492, 22521]",864691135323181212,88951659858256062,"[176176, 102400, 22513]",864691135603849385,89022028602450904,17496,783
7133,"[162702, 96664, 22409]",130273213,159178910632772520,36,"[162692, 96702, 22411]",864691135323181212,87121316595287545,"[162636, 96618, 22406]",864691135125616663,87121316595280309,7188,36
7156,"[174812, 101940, 22543]",151335834,160868447754911788,626,"[174824, 101880, 22547]",864691135323181212,88810853717051679,"[174854, 101872, 22541]",864691136529567199,88810853717043698,5664,626
7170,"[162946, 97170, 22295]",130273453,159249348096426755,50,"[162972, 97120, 22298]",864691135323181212,87191754058831147,"[162912, 97208, 22298]",864691135225571650,87191754058828097,5492,50

In [50]:
len(segs[0])

119

In [47]:
nrn.skeleton.vertices[
    segs[0].to_skel_index
]

array([[619696., 403880., 932280.],
       [620136., 404312., 933360.],
       [621832., 402920., 932040.],
       [624272., 402816., 931920.],
       [625552., 402520., 931680.],
       [628256., 402696., 931880.],
       [629576., 402088., 932040.],
       [629464., 402208., 931960.],
       [632576., 400896., 931640.],
       [634096., 401056., 930960.],
       [636128., 401048., 930840.],
       [637504., 401088., 929920.],
       [640840., 400480., 928360.],
       [642704., 400152., 927440.],
       [641440., 400320., 927560.],
       [643312., 400152., 927520.],
       [645840., 400104., 925760.],
       [646032., 400160., 925600.],
       [647936., 400704., 924240.],
       [650752., 399504., 923160.],
       [651096., 400576., 923120.],
       [649608., 400344., 923560.],
       [651840., 400624., 923120.],
       [654776., 400800., 922720.],
       [656432., 400520., 922560.],
       [658816., 400536., 921640.],
       [658672., 400592., 921720.],
       [660800., 400392., 921280.],
       [662144., 400792., 921120.],
       [664536., 401664., 919680.],
       [666496., 401720., 919040.],
       [669152., 401840., 918520.],
       [669464., 402400., 918160.],
       [671528., 401664., 917880.],
       [670064., 402320., 918000.],
       [673040., 401624., 917880.],
       [673856., 402608., 917400.],
       [674784., 403272., 916480.],
       [677024., 403496., 915040.],
       [679080., 403584., 914840.],
       [681344., 403640., 912560.],
       [683080., 404064., 911920.],
       [686112., 404168., 910440.],
       [684536., 403936., 911840.],
       [685600., 404264., 911040.],
       [686736., 404232., 909960.],
       [689816., 403768., 909960.],
       [690704., 403192., 909080.],
       [693184., 402840., 907640.],
       [696448., 401352., 906040.],
       [694512., 402288., 907240.],
       [696456., 401344., 905920.],
       [699192., 401152., 904080.],
       [700640., 402112., 904040.],
       [701432., 402464., 904160.],
       [704264., 401976., 904160.],
       [703328., 402336., 904280.],
       [705600., 401336., 903160.],
       [708080., 399184., 902200.],
       [707496., 401376., 902600.],
       [709496., 400032., 901840.],
       [710072., 400200., 901680.],
       [712000., 401256., 900720.],
       [711280., 400712., 901320.],
       [713296., 402192., 900240.],
       [713240., 402208., 900240.],
       [716784., 401928., 900240.],
       [715528., 402808., 899760.],
       [717280., 401864., 900320.],
       [718104., 402504., 900360.],
       [719496., 403936., 899520.],
       [721016., 404248., 900520.],
       [720032., 404640., 899800.],
       [721712., 403344., 901160.],
       [724040., 403256., 900760.],
       [725840., 403240., 900360.]])